### ISSUE TITLE
[Bluetooth] Bluetooth Error Handling

### ISSUE THREAD

**Issue by sungjk** [Hyesu/capstone_carcar5talk#27]
> `bluez-simple-agent hci0 XX:XX:XX:XX:XX:XX`
> 
> ERROR:dbus.proxies:Introspect error on :1.0:/: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.2" (uid=1000 pid=4529 comm="/usr/bin/python /usr/bin/bluez-simple-agent hci0 D") interface="org.freedesktop.DBus.Introspectable" member="Introspect" error name="(unset)" requested_reply="0" destination=":1.0" (uid=0 pid=2186 comm="/usr/sbin/bluetoothd ")
> Traceback (most recent call last):
>   File "/usr/bin/bluez-simple-agent", line 102, in <module>
>     path = manager.FindAdapter(args[0])
>   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 70, in **call**
>     return self._proxy_method(_args, *_keywords)
>   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
>     **keywords)
>   File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
>     message, timeout)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Rejected send message, 2 matched rules; type="method_call", sender=":1.2" (uid=1000 pid=4529 comm="/usr/bin/python /usr/bin/bluez-simple-agent hci0 D") interface="org.bluez.Manager" member="FindAdapter" error name="(unset)" requested_reply="0" destination=":1.0" (uid=0 pid=2186 comm="/usr/sbin/bluetoothd ")

If the Bluetooth utility does not see the Bluetooth adapter try the following commands:

`sudo nano /etc/group`
{change line 8 from “lp: x:7:” to “lp: x:7:pi” save and exit}

`sudo reboot`

Reference : http://unix.stackexchange.com/questions/161820/bluetooth-manager-window-wont-open

**Comment by sungjk** [comment]
### Accepting the connection

On certain versions of Debian (Raspbian etc) and maybe some others distros. The server_sock.accept() will by default just hang and never accept a connection - even from a paired device! However, a solution to this is really simple. If you go to /etc/bluetooth/main.conf there is a line which is called Disable Plugins. Add a line or change so it looks like this:-

> DisablePlugins = pnat  

Then restart the Bluetooth service:-
`sudo invoke–rc.d bluetooth restart`

Reference: http://stackoverflow.com/questions/12198198/pybluez-not-accepting-connection
